#!/bin/bash

dialog --title "Questionnaire" --inputbox "Please enter your name" 9 30 2>_1.txt
Q_NAME=$(cat _1.txt)

dialog --menu "$Q_NAME, what music do you like best?" 15 30 5 1 "Classical" 2 "Jazz" 3 "Country" 4 "Other" 5 "K-pop" 2>_2.txt
Q_MUSIC=$(cat _2.txt)

if [ "$Q_MUSIC" == "5" ]; then
	dialog --msgbox "Good choice!" 12 25
fi

sleep 5
dialog --clear
exit 0
