#!/bin/bash

# Generating a random number in the range of 1-100
TARGET=$(((RANDOM % 100) + 1))

# Input box to intake the number
dialog --title "Guessing game" --inputbox "Please enter the guessed number (1-100)" 9 30 2>_8.txt

# G_NUM variable holds the guessed number by the user
G_NUM=$(cat _8.txt)

# TRIALS is the limited number of trials given to the user to guess the number
TRIALS=15

while [ "$TRIALS" -ge 0 ]; do
	if [ "$G_NUM" -eq "$TARGET" ]; then
		dialog --msgbox "Hurray! You are absolutely correct :)" 17 30
		exit 0
	elif [ "$G_NUM" -gt "$TARGET" ]; then
		dialog --msgbox "Too high. Try again :(" 17 30
	elif [ "$G_NUM" -lt "$TARGET" ]; then
		dialog --msgbox "Too low. Try again :(" 17 30
	fi

	# Input box again to intake the number if the response is wrong
	dialog --title "Guessing game" --inputbox "Please enter the guessed number (1-100)" 9 30 2>_9.txt
	G_NUM=$(cat _9.txt)
	TRIALS=$(($TRIALS - 1))
done

sleep 8
dialog --clear

exit 0
